### ISSUE TITLE
Upgrade Grease reference to 1.1.10

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/GsDevKit#29]
I noticed GLASS1 is still referencing Grease 1.0.7.x

Seems to me that an upgrade to 1.1.10 would be good to do. We need (and load) it in Seaside.

**Comment by dalehenrich** [comment]
It turns out that right now Grease is referenced from the master branch:

```Smalltalk
        baseline: 'Grease'
          with: [ 
              spec
                loads: #('Core');
                repository: 'github://GsDevKit/Grease:master/repository' ];
```

And this was done about a year ago:  0b064f9. Same timeframe as original bug report ... so we must have crossed wires back then..GsUpgrader uses the master branch as well ...

Sooo I think we're good ... if not we can discuss in more detail ...
