### ISSUE TITLE
Socket error during SendMail>>readSmtpResult leads to isEmpty MNU

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/GsDevKit#72]
See http://forum.world.st/Issue-358-in-glassdb-Socket-error-during-SendMail-gt-gt-readSmtpResult-leads-to-isEmpty-MNU-td4688306.html

We fixed this by changing the implementation of SendMail>>connect:to: by:

```
connectTo: portNumber on: aHost

"Connect the receiver to the server socket identified by portNumber and aHost. 
 aHost may be the name of the host or its address, 
 or aHost == -1 for <broadcase> , or aHost == nil for IN6ADDR_ANY_INIT .
 portNumber maybe either a SmallInteger, or the String name of a service.
 Returns true if the connection succeeded and false if not."

^ self connectTo: portNumber on: aHost timeoutMs: -1
```

This works for Mariano and me

**Comment by dalehenrich** [comment]
Looking at the code involved, it looks like the old implementation has a 100ms timeout and the suggested implementation has no timeout ... which is consistent with my understanding of the ENOTCONN error ...  the main caveat here is that we need to find a solution that works for GemStone predating the infroduction of GsSocket>>connectTo:on:timeoutMs: ... since this is common code at the moment ...

Interestingly enough it looks like this implementation was aimed at introducting a timeout ... but if this works better then it is a good idea to go with it ... 

The eventual right answer is to implement GsSocket>>connectTo:on:timeoutMs: for the versions of GemStone for which it is missing

**Comment by dalehenrich** [comment]
See [this discussion](http://forum.world.st/How-to-send-mail-from-Gemstone-tp4686799p4850110.html) for more recent details
