### ISSUE TITLE
class migration problem

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#74]
```
- I have a class FaSecurityClosingPriceRecord which has no instance nor subclasses. 
- I have a separate class called FaSecurityClosingPriceRecord2 (yes, don't ask please) which a special superclass and also have 2 subclasses (this is a different hierarchy than  than FaSecurityClosingPriceRecord). Both subclasses do have instances. 

So...what I need to do is remove old class FaSecurityClosingPriceRecord and rename FaSecurityClosingPriceRecord2 to FaSecurityClosingPriceRecord. And of course, migrating the sub instances.  I tried the following (in order)

1) First monticello commit only the removal of FaSecurityClosingPriceRecord. Then upload code, commit and #doBulkMigrate.

2) Monticello commit where I rename FaSecurityClosingPriceRecord2 to FaSecurityClosingPriceRecord (so subclasses now are subclass of FaSecurityClosingPriceRecord). And I made a copy of FaSecurityClosingPriceRecord and call it FaSecurityClosingPriceRecord2. So to sum up, I have both classes (being equal) FaSecurityClosingPriceRecord and FaSecurityClosingPriceRecord2 and just that FaSecurityClosingPriceRecord is the one that has the subclasses.

3) Then I tried something like:

FaSecurityClosingPriceRecord2 addNewVersion: FaSecurityClosingPriceRecord.	System commit. 
FaSecurityClosingPriceRecord2 migrateInstancesTo: FaSecurityClosingPriceRecord.
FaSecurityClosingPriceRecord2 removeFromSystem. 

But that didn't work at all. 

So...how should be the steps I can do to make this refactor/migration? I found no example of classes with subclasses and renaming one in the middle of hierarchy in the guide, so I wonder if this is a special case or not.
```

**Comment by marianopeck** [comment]
Dale, I may have been able to reproduce it. I tried in a GemStone 3.1.0.6. These are the steps:

1) Download `GemStoneClassMigration-MarianoMartinezPeck.1` from `http://smalltalkhub.com/mc/marianopeck/MarianoPublic/main`
2) Execute:
		InstancesPopulator createAndStoreTestingInstances.
		System commit. 
3) I would do a backup now in order to easily restore if you wanted to check a few more things BEFORE the migration/update
4) Letting the default automigratte/autocommit of MC, get version 2: GemStoneClassMigration-MarianoMartinezPeck.2.  Maybe do another `System commit` just in case.
5) Get third version: `GemStoneClassMigration-MarianoMartinezPeck.3`
6) Open Transcript and execute: `BugConfirmer confirmBug`

Could you see how I have more classes/metaclasses for the same class after I load version 2? Please let me know you were able to reproduce it too!!!!!

**Comment by marianopeck** [comment]
mmmm while it is true that there are more metaclasses / classes for the same class, I am not sure if this really reproduces my case since I am finding some little differences. 
Maybe it is just normal to have those metaclasses/classes ?

BTW...I forgot to say...version 1 is like this:

	 Object
	 - ClosingRecord (no instances)
	 - SpecialSuperclass
	 - - ClosingRecord2 ( instances)
	 - - - FSCPR2A (instances)
	 - - - FSCPR2A (instances)

And version2 changes to:

	 Object
	 - SpecialSuperclass
	 - - ClosingRecord (instances)
	 - - - FSCPR2A (instances)
	 - - - FSCPR2B (instances)

**Comment by marianopeck** [comment]
Ouch.... before running `confirmBug` we must be sure to run `SystemRepository markForCollection. SystemRepository reclaimAll.`. Grrr I am not sure if we are able to reproduce it...

**Comment by dalehenrich** [comment]
okay ... I'm taking a stab at reproducing the problem ... thx man ... I'll let you know how it goes

**Comment by dalehenrich** [comment]
@marianopeck here's the results I've seen [running my tode script](https://gist.github.com/dalehenrich/626a3d731fc52f037657) (` ./bug --history` produces the class history hierarchy view):

```
  ./bug --load=GemStoneClassMigration-MarianoMartinezPeck.1
  ./bug --populate 
  ./bug --history
--------------------
Object
 ClosingRecord
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord2
   FSCPR2A
   FSCPR2B

  ./bug --load=GemStoneClassMigration-MarianoMartinezPeck.2
  ./bug --history
--------------------
ClosingRecord2
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  FSCPR2A[1]
  FSCPR2B[1]
```

What I've noticed is that GemStoneClassMigration-MarianoMartinezPeck.3 is exactly the same as GemStoneClassMigration-MarianoMartinezPeck.2 except for the BugConfirmer class, so in my case the class hierarchy and version history will not change ... 

I'm wondering which version of Monticello you might be using ... Here's the Monticello packages I've got loaded:

```
Change-Notification (Change-Notification.v310-dkh.21)
ConfigurationOfGsMonticello (ConfigurationOfGsMonticello-dkh.174)
GemStone-Deployment (GemStone-Deployment.v310-dkh.26)
Monticello (Monticello.v3-dkh.478)
MonticelloGs (MonticelloGs.v33-dkh.2)
PackageInfo-Base (PackageInfo-Base.g-dkh.36)
```

I  **am** running this in 3.3 ... so I will run in a 3.1.0.6 (fully updated) when I get home.

**Comment by dalehenrich** [comment]
@marianopeck I'm seeing the same results for my 3.1.0.6 stone ... here are the monticello packages from my image (no MonticelloGs.v33 package):

```
Change-Notification (Change-Notification.v310-dkh.21)
ConfigurationOfGsMonticello (ConfigurationOfGsMonticello-dkh.173)
GemStone-Deployment (GemStone-Deployment.v310-dkh.26)
Monticello (Monticello.v3-dkh.478)
PackageInfo-Base (PackageInfo-Base.g-dkh.36)
```

**Comment by dalehenrich** [comment]
@marianopeck I just looked at the confirmBug method:) and see that you are getting rid of the class histories and I think I'm finally beginning to understand the "problem" ... I don't know that this is a real problem --- I've never gone around counting metaclasses, so I'll have to wrap my head around what you are seeing ... like I don't understand the third package load as it does not appear to create new classes ... but now that I know that meta classes are the concern I will start tracking things in a little more detail ..

**Comment by dalehenrich** [comment]
@marianopeck I've done the analysis and I think I see the issue ... first the results - I've modified the script to produce a `sample`, which is in class history order showing the oop of class and the metaClass and each sample has a number ... so the samples accumulate doe we can see the oops of the classes and metaClasses as they are created:

```
  ./bug --load=GemStoneClassMigration-MarianoMartinezPeck.1
  ./bug --populate 
  ./bug --history
--------------------
Object
 ClosingRecord
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord2
   FSCPR2A
   FSCPR2B
  ./bug --sample=1; inspect
--------------------
1@               -> '1'->anArray( anArray( 222728449, 222728193))

  ./bug --load=GemStoneClassMigration-MarianoMartinezPeck.2
  ./bug --history
--------------------
ClosingRecord2
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  FSCPR2A[1]
  FSCPR2B[1]
  ./bug --sample=2; inspect

--------------------
1@               -> '1'->anArray( anArray( 222728449, 222728193))
2@               -> '2'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))

  ./bug --load=GemStoneClassMigration-MarianoMartinezPeck.3
  ./bug --history
--------------------
ClosingRecord2
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  FSCPR2A[1]
  FSCPR2B[1]
  ./bug --sample=3; inspect
--------------------
1@               -> '1'->anArray( anArray( 222728449, 222728193))
2@               -> '2'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))
3@               -> '3'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))

  ./bug --gc
  ./bug --reclaim
  ./bug --sample=4; inspect
--------------------
1@               -> '1'->anArray( anArray( 222728449, 222728193))
2@               -> '2'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))
3@               -> '3'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))
4@               -> '4'->anArray( anArray( 222728449, 222728193), anArray( 214259969, 214259713))

  ./bug --confirm
--------------------
none meta:214259969
meta: 214259713
none meta:222728449
meta: 222728193

  ./bug --history
--------------------
Object
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord
   FSCPR2A
   FSCPR2B
```
So presumably the question is "Why is ( 222728449, 222728193) hanging around"

**Comment by dalehenrich** [comment]
From looking at the class history hierarchy the class history has indeed been cleaned up and at this point in time, it is a mystery what is keeping the class/metaClass alive ---- but I know that it isn't the class history and presumably there are no instances of the class lying around ... but that's what I will start looking for tomorrow ...

**Comment by dalehenrich** [comment]
@marianopeck this is our old friend Monticello caching that's holding onto references to the class. Execute the following (and logout) to get rid of the remaining references:

```Smalltalk
MCMethodDefinition resetCachedDefinitions.
MethodVersionHistory reset
```

Gory details of my analysis are [here](https://gist.github.com/dalehenrich/d80ce234667e56a02682) using the final version of the [script](https://gist.github.com/dalehenrich/626a3d731fc52f037657) - note that I used Repository>>findAllReferencePathsToObject: to find the references to the old version of ClosingRecord which is new in 3.2.x (I think)...

**Comment by dalehenrich** [comment]
The root cause of this bug is in GsDeployer>>doBulkMigrate, where we are removing classes from the version history for a class. In Class>>removeFromSystem we clean up the version history with `MethodVersionHistory uniqueInstance removeVersionsForClass: self.` and we should do something similar when we remove the class form the version history in other places (don't forget TDShellTool>>clsRemoveClassFromClassHistory:) ... should also take a look at cleaning up the cached definitions in MCMethodDefinition

**Comment by marianopeck** [comment]
Hi Dale, Thanks for the searching via `findAllReferencePathsToObject:` I was going to do the same. I am happy this helped you to improve tODE command and for the fix of cleaning the MC cache upon removing from system. Both are improvements. 

However... This testcase, did NOT actually reproduced my original problem. The "2 classes and 2 metaclasses" was simply a way to detect the problem, but not because there were holded from other objects. The problem is different. Let me try to explain the difference just in case you can think of something that is different from my real scenario and this test case, that may help me to reproduce it for real.

Remember I start with this:

 Object
 - ClosingRecord (no instances)
 - SpecialSuperclass
 - - ClosingRecord2 ( instances)
 - - - FSCPR2A (instances)
 - - - FSCPR2A (instances)

As you can see in the test case, here I have 100 instances of ClosingRecord2. And version2 changes to:

 Object
 - SpecialSuperclass
 - - ClosingRecord (instances)
 - - - FSCPR2A (instances)
 - - - FSCPR2B (instances)

When I upload code to version2, I still have the 100 instances of ClosingRecord2. If I inspect `(UserGlobals at: #'ClosingRecord2Instances') ` I do get those instances and whose `class` is the deleted  ClosingRecord2. It seems `ClosingRecord2` is only deleted from the namespaces. ClosingRecord has 0 instances.

Well...in my original problem, those instances of what I call here ClosingRecord2 are migrated and after the code update, their `class` is ClosingRecord! But it's a different ClosingRecord class. If take any of those instances and I send `class` and ask OOP or check via `==` such class is NOT the same as the ClosingRecord installed in the namespace. In fact, as soon as I persist a NEW instance of ClosingRecord, that will be instance of the NEW class ClosingRecord. In fact, doing a `(GsObjectInventory profileRepository instanceCountReportDownTo: 1)` will show TWO entries for the same class ClosingRecord, one holding the objects I had BEFORE in ClosingRecord2, and one with the new persistent objects.

So..this is what I am not able to reproduce with this test and which was my original problem. Any idea of what could be the difference? Why would my instances be migrated class in my real problem while not with this case?

**Comment by dalehenrich** [comment]
Welllll, I am only able to analyze what I can see from a test case:) The fact that the instances were not migrated is interesting and probably diagnostic ... with `autoMigrate` turned on the instances should have been migrated ... Instance migration could have been interrupted by the GemStone bug (`45620  C2  Repository>>_scanPomWithMaxThreads:waitForLock:pageBufSize:percentCpuActiveLimit:identSet:limit:scanKind:toDirectory: (prim 896) may return nil`) do you think that might possibly be the case?  If so let's open another issue and try to come up with a test case (perhaps a breakpoint at a critical spot could simulate the error?)

**Comment by marianopeck** [comment]
Dale, when you said "The fact that the instances were not migrated is interesting and probably diagnostic ... with autoMigrate turned on the instances should have been migrated"  that means you are with me in the sense that the following should be true, but we get false `(UserGlobals at: #'ClosingRecord2Instances') allSatisfy: [:each | each class name = #'ClosingRecord']`

? 

BTW, were can I see the details of that issue 45620 C2? I guess it's internal...

**Comment by marianopeck** [comment]
Sorry Dale to insist, but what it really not clear to me is whether such a migration should be automatically performed by Monticello or not. We know the state before the update, and we know what are the changes. What I am not sure (maybe you are, and this is what I am asking), is wether the existing instances of ClosingRecord2 should be migrated as instances of the new ClosingRecord...Because maybe I am doing it wrong, and this should never happen automagically.

**Comment by dalehenrich** [comment]
Okay what I observed in your test case (which did **not** show the migration issue, but was otherwise the same code patters - right?),

After the load of `GemStoneClassMigration-MarianoMartinezPeck.2` you end up with class versions for ClosingRecord:

```
  ./bug --history
--------------------
ClosingRecord2
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  FSCPR2A[1]
  FSCPR2B[1]
```

`ClosingRecord[1]` is the old class version and `ClosingRecord[2]` is the new class version (BTW, this stuff is only visible to you in your development environment if you are using a recent version of tODE:(). Both class versions have a class name of `#ClosingRecord` but they each have a different oop... 

A failure to migrate means that the instances remain instances of `ClosingRecord[1]` (the original class) and their class is not `ClosingRecord[2]` which is the class that is returned by `Smalltalk at: #ClosingRecord`...

**Comment by marianopeck** [comment]
Hi Dale,

Super cool addition of tODE :)   

Now....what you show is different from the scenario I mention above. What I am wondering is about instances of `ClosingRecord2` (note the 2 at the very end of the class name) from version1 if they should have been migrated to class `ClosingRecord`. That's  THE question I have: `#'ClosingRecord2Instances') allSatisfy: [:each | each class name = #'ClosingRecord']`  which used to be instances of `ClosingRecord2`  should have been migrated to instances of `ClosingRecord2`.

I mean, I do understand about the migration of the old class `ClosingRecord` and the new class `ClosingRecord`. My question is about instances of `ClosingRecord2`. 

Maybe using the `2` as the classname is not a good idea because now you are using it as the version number...I should have called it "New"....

Not sure if I could explained myself. Couldn't I?

**Comment by dalehenrich** [comment]
okay ... I really need to see code ... you've got `ClosingRecord2Instances` but it is created by the following:

```Smalltalk
  100
    timesRepeat: [ 
      (UserGlobals
        at: #'ClosingRecord2Instances'
        ifAbsentPut: [ OrderedCollection new ])
        add:
          (ClosingRecord new
            d: 'dd';
            yourself) ].
```

So it is not surprising that the class of the instances in `ClosingRecord2Instances` are instances of `ClosingRecord` ... but now that I know that ClosingRecord2 is where your interest lies  ... let me poke around ... I would also prefer that you open another issue ... since I fixed the bug that was revealed by the test case ... and now we are trying to figure out how to reproduce a different bug:)

**Comment by dalehenrich** [comment]
hmmm... The snippet of code above for  method InstancesPopulator class>>createAndStoreTestingInstances is from `GemStoneClassMigration-MarianoMartinezPeck.2` and the implementation is different from that in `GemStoneClassMigration-MarianoMartinezPeck.1` so I was confused ... I am investigating ...

**Comment by marianopeck** [comment]
Grrrr you are right dale.... Accidently I changed createAndStoreTestingInstances as part of the rename refactor. Sorry. If you see version1 i was:

	100 timesRepeat: [  
		(UserGlobals at: #'ClosingRecord2Instances' ifAbsentPut: [ OrderedCollection new])
			add: (ClosingRecord2 new d: 'dd'; yourself).
		].

So I stored 100 instances of the old ClosingRecord2. These are the instances which in my original case seem to have been migrated automatically to new ClosingRecord. While with this testcase they remain as instances of the deleted class `ClosingRecord2`.

**Comment by dalehenrich** [comment]
Now that I'm looking at `ClosingRecord2` I'm seeing some odd stuff ... but I want to pursue this in a separate issue

**Comment by marianopeck** [comment]
Ok, let's continue in another issue. I will also try to restore again the broken extent and see if I can find more details....

**Comment by dalehenrich** [comment]
Good ... I can definitely see several things wrong here ... but we only need to load `GemStoneClassMigration-MarianoMartinezPeck.2` to wreak havoc:) so the "proof of bug" will be different ...

**Comment by marianopeck** [comment]
Indeed. Version 2 should be enough

**Comment by marianopeck** [comment]
Dale...I tried to restore from the backup I thought was wrong, but it looks like it's not exactly the same as I thought I had. I am sorry, but it seems I do not have a backup as it was exactly at that point, so now it's really hard to know what exactly did happen. 

I don't want you to loose more time with something that now is not even clear....

I am sorry, but I think we should forget/ignore my scenario, and simply check if we can find something wrong with the test case I provided here. And if we can't, then simply ignore this.

Thoughts?

**Comment by dalehenrich** [comment]
One of the things that I thought was a problem was the hierarch showing ClosingRecord2 at the top of the hierarchy:

```
  ./bug --history
--------------------
ClosingRecord2
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  FSCPR2A[1]
  FSCPR2B[1]
```

but that turned out to be a tODE bug (that I fixed:) ... the corrected hierarchy is as follows:

```
  ./bug --history
--------------------
Object
 ClosingRecord[1]
 InstancesPopulator
 SpecialSuperclass
  ClosingRecord[2]
   FSCPR2A[2]
   FSCPR2B[2]
  ClosingRecord2{213207553}
   FSCPR2A[1]
   FSCPR2B[1]
```

Note that `ClosingRecord2{213207553}` shows up in the "right spot" ... The number in the `{}` is the oop of the class and indicates that it is a class that is **not** in Smalltalk - the user's symbol list - and is not in the class history of a class that is in Smalltalk --- basically an Obsolete class like in Pharo ... except that in GemStone's case the a class can be in a SymbolDictionary that is not in the user's SymbolList so seeing an oop with a class does not mean that it is definitely obsolete ... in this case the class **has** been deleted and you can see that the old versions of `FSCPR2A` and `FSCPR2B` do have `ClosingRecord2` as their superclass ... so this hierarchy is complete and correct..

The handling of `ClosingRecord2` was what I thought was a potential problem with this current example ... I've got a bit more analysis to do ...

**Comment by dalehenrich** [comment]
It does not look like we have a problem with this particular example. Three collections created by InstancesPopulator appear to be correct:

```
1@       -> anOrderedCollection( aClosingRecord2, aClosingRecord2, aClosingRecord2, aClosingRecord2, aClosingRecord2, aClosingRecord2, aClosingRecord2, ...
2@       -> anOrderedCollection( aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A, aFSCPR2A,...
3@       -> anOrderedCollection( aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B, aFSCPR2B,...
```

The first collection consists of instances of the deleted class `ClosingRecord2` and the other two collections have migrated instances and here are samples of each class from the collection:

```
(class)@     -> ClosingRecord2
(oop)@       -> 213387265
(committed)@ -> true
c@           -> nil
d@           -> 'dd'
---
(class)@     -> FSCPR2A
(oop)@       -> 212388865
(committed)@ -> true
c@           -> nil
d@           -> 'dd'
e@           -> 'ee'
---
(class)@     -> FSCPR2B
(oop)@       -> 212414465
(committed)@ -> true
c@           -> nil
d@           -> 'dd'
f@           -> 'ff'
```

So everything seems to be correct ... I will take a crack at simulating an error (breakpoint during migration) to see if I can corrupt things - I'll submit a separate bug if I am able to do so ...

Appreciate your patience with this ... we did find a couple of things with the system and tODE that are worth finding ...

**Comment by marianopeck** [comment]
Hi Dale, 

A couple of things:

1) Great addition the one you added to tODE (I love the version number and the OOP for those in no the SystemDictionary :) ) 
2) Indeed, I agree that the hierarchy looks correct and the migrated classes/instances do also look correct. And this is what I failed to reproduce from my original case.
3) No problem with my patience. Thanks for YOUR patience. It is likely I screw it up (not GemStone issue). At least we improved a couple of things. 
4) If you simulate an error during migration like the listing instances one, it is likely that indeed the resulting hierarchy may be broken. But I guess you cannot do much magic if the migration fails, can you? 

Agains, thanks for watching and I will pay attention for future migrations.

**Comment by dalehenrich** [comment]
Well I think I want to make sure that we can do better than silently failing the migration and leaving a mess behind:)

**Comment by marianopeck** [comment]
I think that you will have fun if you modify the `listInstances: anArray limit: aSmallInt toDirectory: directoryString withMaxThreads: maxThreads maxCpuUsage: aPercentage memoryOnly: memOnlyBool` method to do something like this:

                    (anArray first class name = #'FSCPR2A') ifTrue: [ self error: 'or .. answerser  nil? ' ]

Anyway...you get the idea. You now have a tODE command to check hierarchy and you can also inspect the 3 collections of objects stored in UserGlobals.

**Comment by dalehenrich** [comment]
yep that would do it:)
